### ISSUE TITLE
Docusign not available to other colleges

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#1034]
COE User:

![image](https://user-images.githubusercontent.com/469010/94066042-c7637480-fda0-11ea-9fe1-8914886f35e3.png)

**Comment by srkirkland** [comment]
Solution:
Use the same service account in multiple UCD accounts (like CAES &. ENGR) and we only need to get user consent once.

Afterwards, follow the normal instructions on getting an access token and then query the https://account.docusign.com/oauth/userinfo endpoint and you'll see multiple accounts under the "accounts" section. Grab the BaseURI and AccountID, you'll need those values whenever you want to act as behalf of the user in that given account.

**Comment by srkirkland** [comment]
Alright, in order to build this, we'll want to do the following:

- [ ] on the docusign settings page for team admins (ex https://peaks-test.ucdavis.edu/caes-cru/DocumentSettings), remove everything that is there and just display a list of all DocuSign accounts that are available to our service account, which you can get via the API.  If the API is difficult for this step, just copy the default accountID from the secrets file and use that for now

- [ ] when an account is chosen on the docusign settings page, store the accountID and associated docusign baseURL in the database, similar to how we store `TeamApiCode`.  This will require some database modification, and you can remove anything that is there now in the `TeamDocumentSetting` table since that'll no longer be needed.

- [ ] Now modify the `Document` class to include accountID and baseURL for each entry. you'll need them to lookup envelope info.

- [ ] Modify methods in the `DocumentSigningService` so they are account independent -- Wherever we used to pull from `_documentSigningSettings.AccountId` or `_documentSigningSettings.ApiBasePath` we now have to get that information dynamically (either from the document itself or from the team settings).

- [ ] Modify so when you click on `+ Add Document` it uses the team settings to query for the list of templates available instead of pulling from the manually created db list.

I think that should be about it -- the basic overall goal here is that we need to remove the static accountId and ApiBasePath from the config and have it be dynamic based on what a team chooses, and what a specific document was created under.  

Most of the API surface shouldn't have to change much, but there are good C# samples here if you need it https://github.com/docusign/code-examples-csharp and the API reference is good too https://developers.docusign.com/docs/esign-rest-api/reference.

**Comment by sprucely** [comment]
Not finding anything obvious in the esign-rest-api docs linked above. Perhaps getOrganizations in the admin-api (https://developers.docusign.com/docs/admin-api/reference/accounts/accounts/getorganizations/) is what I'm looking for? It includes a list of organizations along with a list of accounts per organization.

**Comment by srkirkland** [comment]
This is the endpoint you want: https://developers.docusign.com/platform/auth/reference/user-info/.  Basically we want to know all of the accounts (not organizations, there is only one ORG) that the service account has access to, and that API endpoint will return that info.
